<<<<<<< HEAD
# Generated by Django 5.0 on 2024-12-12 03:31
=======
# Generated by Django 5.0 on 2024-12-12 03:23
>>>>>>> a71965f30dfb39eac791bd22db57402dfc0723ea

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
        ("auth", "0012_alter_user_first_name_max_length"),
>>>>>>> a71965f30dfb39eac791bd22db57402dfc0723ea
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente_temporal', models.CharField(default='ebed15c5161a49a', max_length=15, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('precio_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTicket',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteApp.producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clienteApp.ticket')),
=======
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id_ticket", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_cliente_temporal",
                    models.CharField(
                        default="e95ec5be3c0a42d", max_length=15, unique=True
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("precio_total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("rut", models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleTicket",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                ("precio_unitario", models.IntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clienteApp.producto",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="clienteApp.ticket",
                    ),
                ),
>>>>>>> a71965f30dfb39eac791bd22db57402dfc0723ea
            ],
        ),
    ]
